[package]
name = "marciemoo"
version = "0.1.0"
edition = "2021"

[dependencies]
logos = "0.13.0"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
sled = "0.34.7"
tokio = { version = "1.32.0", features = ["full", "net"] }
